[workspace]
members = [
    "rorm",
    "rorm-error",
    "rorm-macro",
    "rorm-conn",
    "rorm-query",
    "rorm-test",
    "examples/sqlite/getting_started",
    "examples/mysql/getting_started",
    "examples/conn/sqlite",
]
